services:
  plausible:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.analytics.rule=Host(`analytics.jaalyantra.com`)"
      - "traefik.http.routers.analytics.entrypoints=web"
      - "traefik.http.services.analytics.loadbalancer.server.port=8000"
      - "traefik.http.routers.analytics.entrypoints=websecure"
      - "traefik.http.routers.analytics.tls.certresolver=myresolver"
