services:
  traefik:
    image: traefik:latest
    network_mode: "host"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./acme.json:/acme.json:rw"
      - "./traefik.yml:/etc/traefik/traefik.yml"
      - "./log:/var/log/traefik"
    environment:
      - TRAEFIK_LOG_LEVEL=ERROR
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`${HOST_NAME}`)"
      - "traefik.http.middlewares.authtraefik.basicauth.users=traefikwala:${HASHED_PASSWORD_ENV_VAR}"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.middlewares=authtraefik"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls.certresolver=myresolver"
      - "traefik.http.routers.traefik.middlewares=authtraefik"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 256M
        reservations:
          cpus: "0.25"
          memory: 128M
