version: "3.8"

services:
  traefik:
    image: traefik:latest
    network_mode: "host"
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.docker=true
      - --providers.docker.swarmMode=true
      - --providers.docker.exposedbydefault=true
      - --api.insecure=false
      - --api.dashboard=true
      - --log.level=ERROR
      - --metrics.prometheus=true
      - --metrics.prometheus.entryPoint=websecure
      - --accesslog
      - --accesslog.filepath=/var/log/traefik/access.log
      - --accesslog.bufferingsize=100
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./acme.json:/acme.json:rw"
      - "./traefik.yml:/etc/traefik/traefik.yml"
      - "./log:/var/log/traefik"
    environment:
      - TRAEFIK_PROVIDERS_DOCKER_ENDPOINT=unix:///var/run/docker.sock
      - TRAEFIK_LOG_LEVEL=ERROR
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`{HOST_NAME}`)"
      - "traefik.http.middlewares.authtraefik.basicauth.users=traefikwala:${HASHED_PASSWORD_ENV_VAR}"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls.certresolver=myresolver"
      - "traefik.http.routers.traefik.middlewares=authtraefik"
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 256M
        reservations:
          cpus: "0.25"
          memory: 128M
