global:
  checkNewVersion: true
  sendAnonymousUsage: false

log:
  level: ERROR

api:
  dashboard: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false

certificatesResolvers:
  myresolver:
    acme:
      email: saransh@jaalyantra.com
      storage: /acme.json
      dnsChallenge:
        provider: cloudflare

accessLog:
  filePath: "logs/access.log"
  bufferingSize: 100
